close all;
clear all;
load matlabteste2;
saidafinalvar = saidafinal.signals.values;
result06_float;
saidafloat = saida;
clear saida;
result06_longdouble;
saidald = saida;
clear saida;
result06_change1;
saidach1 = saida;
clear saida;
result05;
saida05 = saida;
VisSimTeste;
TBoutput;
figure(1);
plot(saidafinalvar(1:5000),'b'); 
grid on; 
hold on; 
%plot(saidafloat(:,6),'r');
%plot(saidald(:,6),'y');
%plot(saida05(:,3),'c');
plot(saidach1(:,6),'m*');
plot(data(:,6),'k');
plot(vsmData(:,6),'g');
%legend('Matlab','Mikio-float','Mikio-LD','Mikio-F-05','Mikio-F-ch1','Tuda','VisSim');
legend('Matlab','Mikio-F-ch1','Tuda','VisSim');

saidaMatlab = saidafinalvar(1:5000);
deltaMat = saidaMatlab-saidach1(:,6);
deltaVis = vsmData(:,6)-saidach1(:,6);
figure(2);
plot(deltaMat,'r');
hold on;
plot(deltaVis);
legend('Mikio->Mat','Mik->Vis');
